// Catalogue of wedding invitation templates.
// Folders must match public/templates/<folder>/ exactly.

export type Template = {
  id: string;
  folder: string;
  name: string;
  tagline: string;
  vibe: string;
  palette: string[];
  weddingType:
    | "Hindu"
    | "South Indian"
    | "Muslim Nikah"
    | "Muslim Walima"
    | "Royal Palace"
    | "Garden"
    | "Beach";
  highlight: string;
  /** Image path relative to public/templates/<folder>/ */
  poster: string;
};

export const templates: Template[] = [
  {
    id: "rajwada-royale",
    folder: "template-rajwada-royale",
    name: "Rajwada Royale",
    tagline: "A palace door opens for your big day",
    vibe: "North-Indian royal palace",
    palette: ["#7B1E2B", "#C9A84C", "#F4E6CC"],
    weddingType: "Royal Palace",
    highlight: "Maroon + gold, diya petals, opening doors",
    poster: "assets/couple-vzDcWLv2.webp",
  },
  {
    id: "marigold-bhavan",
    folder: "template-marigold-bhavan",
    name: "Marigold Bhavan",
    tagline: "Sunshine, torans and tradition",
    vibe: "Classic Indian engagement",
    palette: ["#7A6E2A", "#D9A441", "#F1E6C4"],
    weddingType: "Hindu",
    highlight: "Olive + gold, paper envelope, sepia texture",
    poster: "assets/couple-YnNIeptm.webp",
  },
  {
    id: "toran-telugu",
    folder: "template-toran-telugu",
    name: "Toran Telugu",
    tagline: "Banana leaves, brass lamps, South-Indian warmth",
    vibe: "South Indian traditional",
    palette: ["#5B1A1A", "#B68A3D", "#7A8C3A"],
    weddingType: "South Indian",
    highlight: "Maroon + brass + leaf accents",
    poster: "assets/couple-1-pS_ENGcD.jpg",
  },
  {
    id: "ghibli-selfie",
    folder: "template-ghibli-selfie",
    name: "Ghibli Selfie",
    tagline: "Hand-painted, animated, heartfelt",
    vibe: "Ghibli hand-painted",
    palette: ["#E2A89E", "#F4D9B5", "#7FB3A8"],
    weddingType: "Muslim Nikah",
    highlight: "Selfie shutter finale, paper-cut clouds",
    poster: "assets/couple-DN8lYpms.webp",
  },
  {
    id: "emerald-nikah",
    folder: "template-emerald-nikah",
    name: "Emerald Nikah",
    tagline: "Vows under emerald vines",
    vibe: "Emerald Islamic parchment",
    palette: ["#0E3B2E", "#D4AF37", "#F6EBC8"],
    weddingType: "Muslim Nikah",
    highlight: "Emerald + cream, roses and daisies",
    poster: "images/hero-bg.jpg",
  },
  {
    id: "noor-e-zahra",
    folder: "template-noor-e-zahra",
    name: "Noor-e-Zahra",
    tagline: "The nikkah under a moonlit mandala",
    vibe: "Ivory + antique gold Islamic",
    palette: ["#F5EBC8", "#B58A2C", "#7C8B3F"],
    weddingType: "Muslim Nikah",
    highlight: "Mandala texture, Arabic blessing",
    poster: "images/bride.jpg",
  },
  {
    id: "royal-reception",
    folder: "template-royal-reception",
    name: "Royal Reception",
    tagline: "A grand reception under aurora lights",
    vibe: "Royal blue reception",
    palette: ["#1F2A6E", "#E8D49A", "#F4ECD8"],
    weddingType: "Muslim Walima",
    highlight: "Royal blue + ivory, aurora shimmer",
    poster: "images/couple-hero.png",
  },
  {
    id: "kerala-sands",
    folder: "template-kerala-sands",
    name: "Kerala Sands",
    tagline: "Temple bells, the sea, and jasmine",
    vibe: "Kerala traditional",
    palette: ["#F6EFD9", "#C29A48", "#7A6E40"],
    weddingType: "South Indian",
    highlight: "Ivory + gold coastal ceremony",
    poster: "images/couple-hero.webp",
  },
  {
    id: "meadow-nikah",
    folder: "template-meadow-nikah",
    name: "Meadow Nikah",
    tagline: "A nikah in a sunlit garden",
    vibe: "Garden outdoor Nikah",
    palette: ["#A4C8E1", "#A8C97F", "#E9C9D6"],
    weddingType: "Muslim Nikah",
    highlight: "Sky + meadow + blossom, envelope intro",
    poster: "wedding/hero.jpg",
  },
  {
    id: "grand-line-voyage",
    folder: "template-grand-line-voyage",
    name: "Grand Line Voyage",
    tagline: "Set sail for forever",
    vibe: "Anime adventure",
    palette: ["#1F8FCE", "#E0A82E", "#F5DC95"],
    weddingType: "Beach",
    highlight: "Ocean voyage, sunset Goa energy",
    poster: "op-hero-ship.webp",
  },
  {
    id: "sage-parchment",
    folder: "template-sage-parchment",
    name: "Sage Parchment",
    tagline: "Two families, one parchment",
    vibe: "Sage + parchment classic",
    palette: ["#E9DDC4", "#A1B79B", "#5F6E5A"],
    weddingType: "Hindu",
    highlight: "Parchment + sage, open-gate intro",
    poster: "assets/hero-arch-DWGeQd7m.jpg",
  },
  {
    id: "ghibli-portrait",
    folder: "template-ghibli-portrait",
    name: "Ghibli Portrait",
    tagline: "From childhood sketches to the wedding aisle",
    vibe: "Illustrated portrait story",
    palette: ["#E3B89C", "#D6B47C", "#F2E1C5"],
    weddingType: "Garden",
    highlight: "Portrait journey, watercolor florals",
    poster: "images/portrait-bride.webp",
  },
  {
    id: "rajwada-royale-alt",
    folder: "template-rajwada-royale-alt",
    name: "Rajwada Royale Alt",
    tagline: "The palace sample with another couple",
    vibe: "North-Indian royal palace",
    palette: ["#7B1E2B", "#C9A84C", "#F4E6CC"],
    weddingType: "Royal Palace",
    highlight: "Alternate demo of Rajwada Royale",
    poster: "assets/couple-vzDcWLv2.webp",
  },
  {
    id: "marigold-bhavan-alt",
    folder: "template-marigold-bhavan-alt",
    name: "Marigold Bhavan Alt",
    tagline: "The bhavan sample with another couple",
    vibe: "Classic Indian engagement",
    palette: ["#7A6E2A", "#D9A441", "#F1E6C4"],
    weddingType: "Hindu",
    highlight: "Alternate demo of Marigold Bhavan",
    poster: "assets/couple-YnNIeptm.webp",
  },
  {
    id: "rajmahal-palace",
    folder: "template-rajmahal-palace",
    name: "Rajmahal Palace",
    tagline: "Palace doors open onto forever",
    vibe: "Dark royal palace doors",
    palette: ["#3B0712", "#D9A441", "#F1DFB1"],
    weddingType: "Royal Palace",
    highlight: "Deep maroon + gold, opening doors",
    poster: "assets/hero-bg.webp",
  },
  {
    id: "shubha-vivaham",
    folder: "template-shubha-vivaham",
    name: "Shubha Vivaham",
    tagline: "A muhurtham invitation, beautifully told",
    vibe: "South Indian muhurtham with toran",
    palette: ["#6D1A2E", "#F6B93B", "#FFF9EF"],
    weddingType: "South Indian",
    highlight: "Marigold toran, festive parchment",
    poster: "assets/og-image.jpg",
  },
  {
    id: "midnight-stargaze",
    folder: "template-midnight-stargaze",
    name: "Midnight Stargaze",
    tagline: "Vows under a starlit sky",
    vibe: "Navy + gold midnight doors",
    palette: ["#0C0A24", "#E2C88F", "#F5EEE2"],
    weddingType: "Royal Palace",
    highlight: "Doors open under a sky of stars",
    poster: "assets/og-image.jpg",
  },
  {
    id: "kalyana-mandapam",
    folder: "template-kalyana-mandapam",
    name: "Kalyana Mandapam",
    tagline: "The sacred muhurtham, beautifully told",
    vibe: "Mandapam ceremony invitation",
    palette: ["#F7EFDB", "#7B1E1E", "#9A6B1F"],
    weddingType: "South Indian",
    highlight: "Mandapam, parchment + kumkum",
    poster: "assets/og-image.jpg",
  },
  {
    id: "tamil-thirumana",
    folder: "template-tamil-thirumana",
    name: "Tamil Thirumana",
    tagline: "The sacred knot at dawn",
    vibe: "Tamil wedding tradition",
    palette: ["#5B1A1A", "#B68A3D", "#1F6B4A"],
    weddingType: "South Indian",
    highlight: "Banana-leaf palette, dawn ceremony",
    poster: "assets/couple-1-pS_ENGcD.jpg",
  },
  {
    id: "lake-pichola",
    folder: "template-lake-pichola",
    name: "Lake Pichola Royal",
    tagline: "Palace reflections on Lake Pichola",
    vibe: "Royal palace by the lake",
    palette: ["#F2E4C3", "#B8912F", "#8A6A1F"],
    weddingType: "Royal Palace",
    highlight: "Gold floral texture, illustrated couple",
    poster: "assets/couple.webp",
  },
  {
    id: "petal-path",
    folder: "template-petal-path",
    name: "Petal Path Palace",
    tagline: "Walk the petal aisle into forever",
    vibe: "Layered parallax Sikh palace wedding",
    palette: ["#2A1830", "#C45A7A", "#F2C4D0", "#C9A86A"],
    weddingType: "Royal Palace",
    highlight: "5-layer parallax, floral arch, falling petals",
    poster: "assets/layers/source-full.png",
  },
  {
    id: "ivory-waltz",
    folder: "template-ivory-waltz",
    name: "Ivory Waltz",
    tagline: "A soft dance into forever",
    vibe: "Cream linen faceless couple parallax",
    palette: ["#F3EDE3", "#1A1814", "#FFFFFF", "#8A7A68"],
    weddingType: "Muslim Nikah",
    highlight: "Layered parallax dance, calla lilies, soft paper gate",
    poster: "assets/layers/hero-composite.jpg",
  },
  {
    id: "lakeview-lanterns",
    folder: "template-lakeview-lanterns",
    name: "Lakeview Lanterns",
    tagline: "Twilight vows by the glowing backwaters",
    vibe: "Kerala lakeside lantern night",
    palette: ["#1A0B24", "#8E2856", "#D4AF37"],
    weddingType: "South Indian",
    highlight: "Parallax layers, flying lanterns, illustrated couple",
    poster: "assets/reference.png",
  },
];

export const TOTAL = templates.length;
