// Catalogue of all 20 wedding invitation templates.
// Each entry points to a folder under the repo root. When the
// landing page is served next to the templates (e.g. via Netlify),
// the `preview` URL resolves to the deployed build of that template.

export type Template = {
  id: string;
  folder: string;        // repo folder
  name: string;          // brand name
  tagline: string;
  vibe: string;
  palette: string[];     // accent colors for the preview chip
  language: "Telugu" | "Tamil" | "Hindi" | "Urdu" | "Malayalam" | "Bengali" | "Sanskrit" | "English" | "Mixed";
  weddingType:
    | "Hindu"
    | "South Indian"
    | "Muslim Nikah"
    | "Muslim Walima"
    | "Royal Palace"
    | "Garden"
    | "Beach";
  highlight: string;     // one-line pitch
};

// Order matters - this is the order the gallery shows them in.
export const templates: Template[] = [
  {
    id: "rajwada-royale",
    folder: "template-rajwada-royale",
    name: "Rajwada Royale",
    tagline: "A palace door opens for your big day",
    vibe: "North-Indian royal palace",
    palette: ["#7B1E2B", "#C9A84C", "#F4E6CC"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Maroon + gold, diya petals, opening doors",
  },
  {
    id: "marigold-bhavan",
    folder: "template-marigold-bhavan",
    name: "Marigold Bhavan",
    tagline: "Sunshine, torans & tradition",
    vibe: "Classic Indian engagement",
    palette: ["#7A6E2A", "#D9A441", "#F1E6C4"],
    language: "Hindi",
    weddingType: "Hindu",
    highlight: "Olive + gold, paper envelope, sepia texture",
  },
  {
    id: "toran-telugu",
    folder: "template-toran-telugu",
    name: "Toran Telugu",
    tagline: "Banana leaves, brass lamps, big South-Indian warmth",
    vibe: "South Indian Telugu",
    palette: ["#5B1A1A", "#B68A3D", "#7A8C3A"],
    language: "Telugu",
    weddingType: "South Indian",
    highlight: "Maroon + brass + leaf, Telugu typography",
  },
  {
    id: "ghibli-selfie",
    folder: "template-ghibli-selfie",
    name: "Ghibli Selfie",
    tagline: "Hand-painted, animated, heartfelt",
    vibe: "Ghibli hand-painted",
    palette: ["#E2A89E", "#F4D9B5", "#7FB3A8"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Selfie shutter finale, paper-cut clouds",
  },
  {
    id: "emerald-nikah",
    folder: "template-emerald-nikah",
    name: "Emerald Nikah",
    tagline: "Vows under emerald vines",
    vibe: "Emerald Islamic parchment",
    palette: ["#0E3B2E", "#D4AF37", "#F6EBC8"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Emerald + cream, roses & daisies",
  },
  {
    id: "noor-e-zahra",
    folder: "template-noor-e-zahra",
    name: "Noor-e-Zahra",
    tagline: "The nikkah under a moonlit mandala",
    vibe: "Ivory + antique gold Islamic",
    palette: ["#F5EBC8", "#B58A2C", "#7C8B3F"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Mandala texture, Bismillah in Arabic",
  },
  {
    id: "royal-reception",
    folder: "template-royal-reception",
    name: "Royal Reception",
    tagline: "A grand reception under aurora lights",
    vibe: "Royal blue reception",
    palette: ["#1F2A6E", "#E8D49A", "#F4ECD8"],
    language: "Urdu",
    weddingType: "Muslim Walima",
    highlight: "Royal blue + ivory, aurora shimmer",
  },
  {
    id: "kerala-sands",
    folder: "template-kerala-sands",
    name: "Kerala Sands",
    tagline: "Temple bells, the sea, and jasmine",
    vibe: "Kerala traditional",
    palette: ["#F6EFD9", "#C29A48", "#7A6E40"],
    language: "Malayalam",
    weddingType: "South Indian",
    highlight: "Taj Malabar backdrop, ivory + gold",
  },
  {
    id: "meadow-nikah",
    folder: "template-meadow-nikah",
    name: "Meadow Nikah",
    tagline: "A nikah in a sunlit garden",
    vibe: "Garden outdoor Nikah",
    palette: ["#A4C8E1", "#A8C97F", "#E9C9D6"],
    language: "Urdu",
    weddingType: "Muslim Nikah",
    highlight: "Sky + meadow + blossom, envelope intro",
  },
  {
    id: "grand-line-voyage",
    folder: "template-grand-line-voyage",
    name: "Grand Line Voyage",
    tagline: "Set sail for forever",
    vibe: "Anime / One Piece adventure",
    palette: ["#1F8FCE", "#E0A82E", "#F5DC95"],
    language: "English",
    weddingType: "Beach",
    highlight: "Log Pose, sunset Goa, anime typography",
  },
  {
    id: "sage-parchment",
    folder: "template-sage-parchment",
    name: "Sage Parchment",
    tagline: "Two families, one parchment",
    vibe: "Sage + parchment classic",
    palette: ["#E9DDC4", "#A1B79B", "#5F6E5A"],
    language: "Hindi",
    weddingType: "Hindu",
    highlight: "Parchment + sage, open-gate intro",
  },
  {
    id: "ghibli-portrait",
    folder: "template-ghibli-portrait",
    name: "Ghibli Portrait",
    tagline: "From childhood sketches to the wedding aisle",
    vibe: "English Ghibli portrait",
    palette: ["#E3B89C", "#D6B47C", "#F2E1C5"],
    language: "English",
    weddingType: "Garden",
    highlight: "Ghibli portraits, watercolor florals",
  },
  {
    id: "rajwada-royale-alt",
    folder: "template-rajwada-royale-alt",
    name: "Rajwada Royale (Alt)",
    tagline: "Same palace, another couple",
    vibe: "North-Indian royal palace",
    palette: ["#7B1E2B", "#C9A84C", "#F4E6CC"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Alternate demo of Rajwada Royale",
  },
  {
    id: "marigold-bhavan-alt",
    folder: "template-marigold-bhavan-alt",
    name: "Marigold Bhavan (Alt)",
    tagline: "Same bhavan, another couple",
    vibe: "Classic Indian engagement",
    palette: ["#7A6E2A", "#D9A441", "#F1E6C4"],
    language: "Hindi",
    weddingType: "Hindu",
    highlight: "Alternate demo of Marigold Bhavan",
  },
  {
    id: "rajmahal-palace",
    folder: "template-rajmahal-palace",
    name: "Rajmahal Palace",
    tagline: "Palace doors open onto forever",
    vibe: "Dark royal palace doors",
    palette: ["#3B0712", "#D9A441", "#F1DFB1"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Deep maroon + gold, opening doors",
  },
  {
    id: "shubha-vivaham",
    folder: "template-shubha-vivaham",
    name: "Shubha Vivaham",
    tagline: "శుభ వివాహం - a Telugu muhurtham",
    vibe: "Telugu muhurtham with toran",
    palette: ["#6D1A2E", "#F6B93B", "#FFF9EF"],
    language: "Telugu",
    weddingType: "South Indian",
    highlight: "Marigold toran, Telugu shubha vivaham",
  },
  {
    id: "midnight-stargaze",
    folder: "template-midnight-stargaze",
    name: "Midnight Stargaze",
    tagline: "Vows under a starlit sky",
    vibe: "Navy + gold midnight doors",
    palette: ["#0C0A24", "#E2C88F", "#F5EEE2"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Doors open under a sky of stars",
  },
  {
    id: "kalyana-mandapam",
    folder: "template-kalyana-mandapam",
    name: "Kalyana Mandapam",
    tagline: "The sacred muhurtham, beautifully told",
    vibe: "Telugu muhurtham mandapam",
    palette: ["#F7EFDB", "#7B1E1E", "#9A6B1F"],
    language: "Telugu",
    weddingType: "South Indian",
    highlight: "Telugu mandapam, parchment + kumkum",
  },
  {
    id: "tamil-thirumana",
    folder: "template-tamil-thirumana",
    name: "Tamil Thirumana",
    tagline: "முகூர்த்தம் - the sacred knot at dawn",
    vibe: "Tamil wedding Coimbatore",
    palette: ["#5B1A1A", "#B68A3D", "#1F6B4A"],
    language: "Tamil",
    weddingType: "South Indian",
    highlight: "Tamil typography, banana leaf palette",
  },
  {
    id: "lake-pichola",
    folder: "template-lake-pichola",
    name: "Lake Pichola Royal",
    tagline: "Palace reflections on Lake Pichola",
    vibe: "Royal palace by the lake",
    palette: ["#F2E4C3", "#B8912F", "#8A6A1F"],
    language: "Hindi",
    weddingType: "Royal Palace",
    highlight: "Gold floral texture, illustrated couple",
  },
];

export const TOTAL = templates.length;