/* details.js — invitation card, map & hospitality
   Family invitation wording, date/time/venue/weather, calendar buttons, the
   embedded Google Map with Maps/Uber links and the three hospitality cards.
   Text comes from weddingData (venue, weather, hospitality…). */

import { icon } from "../scripts/icons.js";
import { weddingGoogleUrl } from "../scripts/calendar.js";

export function renderDetails(d) {
  const invitationCard = `
<div class="transition-transform duration-200 ease-out" style="perspective: 1000px;"><div data-tilt data-tilt-intensity="6" class="relative overflow-hidden " style="transform: rotateX(0deg) rotateY(0deg); transform-style: preserve-3d; transition: transform 0.15s ease-out;"><div class="glass-twilight royal-corners overflow-hidden rounded-3xl p-8 sm:p-12 shadow-[0_25px_60px_rgba(0,0,0,0.6)] backdrop-blur-2xl text-center"><span class="font-royal text-[10px] font-bold uppercase tracking-[0.4em] text-[#ffd768] bg-[#070b14] px-4 py-1.5 rounded-full border border-[#dfb141]/50 shadow-sm">Main Wedding Mandap</span><h3 class="font-royal mt-6 text-2xl sm:text-3xl font-bold uppercase tracking-[0.2em] text-[#f8edd1]">${d.dateLabel}</h3><p class="gold-text-glow font-script mt-2 text-5xl sm:text-6xl">${d.timeLabel}</p><div class="ornament my-6 text-lg"><span>✦</span></div><div class="flex items-center justify-center gap-2.5 text-[#f8edd1] font-bold text-sm sm:text-base max-w-lg mx-auto">${icon("map-pin", "h-5 w-5 text-[#ffd768] shrink-0")}<span>${d.venue}</span></div><div class="mt-5 inline-flex items-center gap-2 rounded-full bg-[#070b14]/80 border border-[#dfb141]/35 px-5 py-2 text-xs text-[#e6d3a3] shadow-inner">${icon("sun", "h-4 w-4 text-[#ffd768]")}<span>Udaipur Weather: ${d.weather.temp} • ${d.weather.forecast}</span></div><div class="mt-8 grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-md mx-auto"><button id="details-ics" class="flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[#dfb141] via-[#ffd768] to-[#dfb141] px-6 py-3.5 font-royal text-xs font-bold uppercase tracking-[0.2em] text-[#070b14] shadow-[0_0_20px_rgba(223,177,65,0.35)] transition-all hover:scale-105 hover:shadow-[0_0_30px_rgba(223,177,65,0.5)] active:scale-95">${icon("calendar", "h-4 w-4")}<span>Apple / Outlook (.ics)</span></button><a href="${weddingGoogleUrl(d)}" target="_blank" rel="noreferrer" class="flex items-center justify-center gap-2 rounded-full border border-[#dfb141]/60 bg-[#121c33] px-6 py-3.5 font-royal text-xs font-bold uppercase tracking-[0.2em] text-[#ffd768] transition-all hover:bg-[#1a2849] hover:border-[#dfb141] hover:scale-105 active:scale-95 shadow-md">${icon("calendar", "h-4 w-4 text-[#ffd768]")}<span>Google Calendar</span></a></div></div><div class="pointer-events-none absolute inset-0 transition-opacity duration-300" style="opacity: 0; background: radial-gradient(circle, rgba(255, 235, 175, 0.45) 0%, transparent 60%); mix-blend-mode: overlay;"></div></div></div>
  `;

  const hospitality = [
    { icon: "plane", title: "Airport Travel", text: d.hospitality.airport },
    { icon: "hotel", title: "Stay & Check-In", text: d.hospitality.checkIn },
    { icon: "phone", title: "Wedding Concierge", text: d.hospitality.concierge },
  ];
  const hospitalityCard = (ic, title, text) => `
<div class="glass-twilight rounded-2xl p-5 shadow-md"><div class="flex items-center gap-2.5 text-[#ffd768] font-royal text-xs font-bold uppercase tracking-wider">${icon(ic, "h-4 w-4 text-[#dfb141]")}<span>${title}</span></div><p class="font-serif-display mt-2 text-xs text-[#dcd1ba]">${text}</p></div>
  `;
  const hospitalityCards = hospitality.map((c) => hospitalityCard(c.icon, c.title, c.text)).join("");

  return `
<section id="details" class="reveal relative bg-gradient-to-b from-[#070b14] via-[#0d1629] to-[#070b14] px-6 py-32"><div class="mx-auto max-w-4xl text-center"><div class="inline-flex items-center gap-2.5 rounded-full border border-[#dfb141]/40 bg-[#0d1527]/90 px-5 py-2 shadow-lg backdrop-blur-xl">${icon("sparkles", "h-3.5 w-3.5 text-[#ffd768]")}<span class="font-royal text-[11px] font-bold uppercase tracking-[0.35em] text-[#ffd768]">Royal Venue &amp; Hospitality</span>${icon("sparkles", "h-3.5 w-3.5 text-[#ffd768]")}</div><h2 class="gold-text-glow font-script mt-4 text-6xl sm:text-7xl">The Palatial Destination</h2><p class="font-royal mt-2 text-xl font-bold uppercase tracking-[0.25em] text-[#f8edd1]">Lake Pichola, Udaipur</p><div class="ornament my-6 text-xl"><span>✦</span></div><div class="mx-auto max-w-2xl rounded-3xl border border-[#dfb141]/35 bg-[#0d1527]/80 p-6 sm:p-8 backdrop-blur-xl shadow-2xl"><p class="font-royal text-xs font-bold uppercase tracking-[0.35em] text-[#ffd768]">Together With Their Families</p><div class="font-serif-display mt-3 text-sm leading-relaxed text-[#e6d3a3]"><p class="font-bold text-base sm:text-lg text-[#f8edd1]">${d.groomFullName} <span class="text-xs font-medium text-[#ffd768]">(${d.groomFamily})</span></p><p class="font-script text-3xl text-[#dfb141] my-1.5">&amp;</p><p class="font-bold text-base sm:text-lg text-[#f8edd1]">${d.brideFullName} <span class="text-xs font-medium text-[#ffd768]">(${d.brideFamily})</span></p></div><p class="font-serif-display italic text-xs sm:text-sm text-[#c9bea7] pt-3">humbly request the honour of your presence and blessings at the sacred wedding ceremonies.</p></div><div class="mt-14">${invitationCard}
</div><div class="glass-twilight mt-12 overflow-hidden rounded-3xl shadow-2xl text-left border border-[#dfb141]/40"><iframe title="Venue location map" src="https://maps.google.com/maps?q=${encodeURIComponent(d.mapQuery)}&amp;output=embed" class="h-80 w-full border-0 brightness-90 contrast-110" loading="lazy"></iframe><div class="flex flex-col sm:flex-row items-center justify-between gap-4 bg-[#0d1527] px-6 py-4 border-t border-[#dfb141]/25"><a href="${d.mapsUrl}" target="_blank" rel="noreferrer" class="flex items-center gap-2 font-royal text-xs font-bold uppercase tracking-[0.2em] text-[#ffd768] hover:text-white transition-colors">${icon("navigation", "h-4 w-4 text-[#ffd768]")}<span>Open in Google Maps</span>${icon("external-link", "h-3.5 w-3.5 opacity-70")}</a><a href="${d.uberUrl}" target="_blank" rel="noreferrer" class="flex items-center gap-2 font-royal text-xs font-bold uppercase tracking-[0.2em] text-[#f8edd1] hover:text-[#ffd768] transition-colors">${icon("car", "h-4 w-4 text-[#ffd768]")}<span>Book Ride with Uber</span></a></div></div><div class="mt-12 grid grid-cols-1 md:grid-cols-3 gap-6 text-left">${hospitalityCards}
</div></div></div></section>
  `;
}
