/* dock.js — floating “dynamic island” control bar
   Bottom pill with the Melody (music) toggle, quick links and the Release
   Lantern button with its live counter. Behaviour lives in scripts/dock.js. */

import { icon } from "../scripts/icons.js";

/* markup for the two states of the Melody button (scripts/dock.js swaps them) */
export const musicIdleHtml = `${icon("volume-x", "h-3.5 w-3.5 text-[#dfb141]/70")}<span class="font-royal text-[10px] font-bold tracking-wider hidden sm:inline">Melody</span>`;
export const musicPlayingHtml = `<span class="flex items-end gap-0.5 h-3.5 w-3.5"><span class="w-0.5 bg-[#dfb141] rounded-full animate-[equalizer_0.6s_ease-in-out_infinite]"></span><span class="w-0.5 bg-[#dfb141] rounded-full animate-[equalizer_0.9s_ease-in-out_infinite_0.2s]"></span><span class="w-0.5 bg-[#dfb141] rounded-full animate-[equalizer_0.7s_ease-in-out_infinite_0.4s]"></span></span>${icon("volume-2", "h-3.5 w-3.5 text-[#dfb141]")}<span class="font-royal text-[10px] font-bold tracking-wider hidden sm:inline">Sitar On</span>`;

export function renderDock(d) {
  const musicIdle = musicIdleHtml;
  return `<div id="dock" class="fixed bottom-6 inset-x-0 z-40 flex justify-center px-4 pointer-events-none"><div class="pointer-events-auto flex items-center gap-2 rounded-full border border-[#dfb141]/50 bg-[#0d1527]/90 px-3.5 py-2.5 shadow-[0_15px_40px_rgba(0,0,0,0.7)] backdrop-blur-2xl transition-all duration-300 hover:border-[#dfb141] hover:scale-[1.02]"><button type="button" id="dock-music" class="flex items-center gap-2 rounded-full bg-[#121c33] px-3.5 py-1.5 text-xs text-[#dfb141] transition-all hover:bg-[#1a2849] hover:text-white" title="Toggle Royal Sitar Melody">${musicIdle}</button><span class="h-4 w-px bg-[#dfb141]/30"></span><div class="flex items-center gap-1 sm:gap-2"><a href="#story" class="rounded-full px-2.5 py-1 text-[11px] font-royal font-bold uppercase tracking-wider text-[#e6d3a3] hover:text-[#dfb141] transition-colors">Story</a><a href="#itinerary" class="rounded-full px-2.5 py-1 text-[11px] font-royal font-bold uppercase tracking-wider text-[#e6d3a3] hover:text-[#dfb141] transition-colors">Events</a><a href="#details" class="rounded-full px-2.5 py-1 text-[11px] font-royal font-bold uppercase tracking-wider text-[#e6d3a3] hover:text-[#dfb141] transition-colors">Venue</a></div><span class="h-4 w-px bg-[#dfb141]/30"></span><button id="dock-lantern" class="group flex items-center gap-1.5 rounded-full bg-gradient-to-r from-[#dfb141] via-[#ffd768] to-[#dfb141] px-3.5 py-1.5 font-royal text-[10px] font-bold uppercase tracking-wider text-[#070b14] shadow-md transition-all hover:scale-105 active:scale-95" title="Release a glowing sky lantern over Lake Pichola">${icon("flame", "h-3.5 w-3.5 fill-[#070b14] text-[#070b14] animate-pulse")}<span>Release Lantern</span><span id="dock-lantern-count" class="rounded-full bg-[#070b14]/20 px-1.5 py-0.2 text-[9px] font-mono">${d.startLanterns}</span></button></div></div>`;
}
