/* footer.js — closing thanks, portrait, hashtag & back-to-top
   Ending screen with the couple portrait, the copy-hashtag button (scripts/footer.js
   shows the confirmation + confetti) and the Back-to-Top link. */

import { icon } from "../scripts/icons.js";

export function renderFooter(d) {
  return `<footer class="reveal relative flex flex-col items-center justify-end overflow-hidden bg-gradient-to-b from-[#070b14] via-[#09101f] to-[#04070d] px-6 pt-28 pb-24 text-center"><div class="relative z-10 mx-auto max-w-2xl flex flex-col items-center"><p class="gold-text-glow font-script text-6xl sm:text-7xl">With Love &amp; Gratitude</p><p class="font-serif-display mt-3 italic text-sm text-[#dcd1ba] max-w-lg font-normal">"We cannot wait to share the sacred moments, laughter, and timeless memories of our wedding with you under the Udaipur skies."</p><div class="glass-twilight mt-12 w-full max-w-sm overflow-hidden rounded-t-[11rem] rounded-b-3xl p-4 shadow-[0_20px_50px_rgba(0,0,0,0.8)] border border-[#dfb141]/50 transition-transform duration-500 hover:scale-[1.02]"><div class="overflow-hidden rounded-t-[10.5rem] rounded-b-2xl border border-[#dfb141]/40"><img alt="Royal Portrait of Aarav &amp; Ananya at Lake Pichola" class="w-full object-cover brightness-95 transition-transform duration-700 hover:scale-105" src="assets/images/royal-couple.jpg"></div><div class="pt-6 pb-3"><h4 class="gold-text-glow font-script text-5xl sm:text-6xl">${d.groom} &amp; ${d.bride}</h4><p class="font-royal mt-1 text-[11px] font-bold uppercase tracking-[0.3em] text-[#ffd768]">The Royal Pichola Vivah</p><p class="font-serif-display text-xs text-[#c9bea7] mt-1">${d.city} • February 2026</p></div></div><div class="mt-9 flex flex-col items-center gap-3"><button id="footer-hashtag" class="group flex items-center gap-2.5 rounded-full border border-[#dfb141]/70 bg-[#0d1527] px-8 py-3.5 shadow-lg backdrop-blur-xl transition-all hover:bg-[#141f38] hover:border-[#dfb141] hover:scale-105 active:scale-95"><span class="font-royal text-xs font-bold uppercase tracking-[0.25em] text-[#ffd768]">${d.hashtag}</span>${icon("copy", "h-3.5 w-3.5 text-[#dfb141] group-hover:text-white")}</button><span class="text-xs text-emerald-400 font-bold animate-fade-in" id="footer-copied" hidden>✨ Official hashtag copied! Tag your royal stories!</span></div><button id="footer-top" class="mt-8 inline-flex items-center gap-1.5 font-royal text-[11px] font-bold uppercase tracking-[0.25em] text-[#dfb141] hover:text-white transition-colors">${icon("arrow-up", "h-4 w-4")}<span>Back to Top</span></button><div class="mt-14 border-t border-[#dfb141]/20 pt-6 w-full flex flex-col items-center"><p class="font-royal flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-[0.3em] text-[#c9bea7]">Handcrafted with ${icon("heart", "h-3.5 w-3.5 fill-[#c41e3a] text-[#c41e3a] inline")} for ${d.groom} &amp; ${d.bride}</p><a href="https://www.instagram.com/invitestory.in/" target="_blank" rel="noreferrer" class="mt-2.5 inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.25em] text-[#dfb141] hover:text-white transition-colors">${icon("instagram", "h-3.5 w-3.5")}<span>Follow @invitestory.in</span></a></div></div></footer>`;
}
